services:
  mysql:
    container_name: {namespace}-shared-mysql
    restart: always
    build:
      context: .
      dockerfile: environment/mysql/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    environment:
      - MYSQL_DATABASE=pricing_shared_db
      - MYSQL_USER=pricing
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    networks:
      - pricing_network
    volumes:
      - ./environment/mysql/data:/var/lib/mysql