services:
  localstack:
    container_name: localstack
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "4566-4599:4566-4599"
    environment:
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - SERVICES=s3,lambda,sns,sqs
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"